### ISSUE TITLE
Kitti vs nuscene

### ISSUE THREAD

**Issue by wolf943134497** [fzhiheng/RoGS#7]
Hi @fzhiheng Thanks for your great works.

I test rogs on Kitti and nuscene dataset.
The results are much worse on kitti than nuscene. bev_image has very good results on nuscene.
The main reason for the poor effect is the fewer number of cameras (6 vs 2) or the lack of lidar？or any other reason? Thanks

**Comment by splendidjie** [comment]
Excuse me, I encountered this problem when rendering. Do you know how to solve it?
Traceback (most recent call last):
  File "train.py", line 449, in <module>
    train(configs)
  File "train.py", line 229, in train
    render_pkg = render(viewpoint_cam, gaussians, pipe, bg)
  File "/home/kj/A_file/Grad_design/RoGs/RoGS/utils/render.py", line 102, in render
    tanfovx=tanfovx,
UnboundLocalError: local variable 'tanfovx' referenced before assignment

**Comment by fzhiheng** [comment]
> Hi [@fzhiheng](https://github.com/fzhiheng) Thanks for your great works.
> 
> I test rogs on Kitti and nuscene dataset. The results are much worse on kitti than nuscene. bev_image has very good results on nuscene. The main reason for the poor effect is the fewer number of cameras (6 vs 2) or the lack of lidar？or any other reason? Thanks

The main reason for this is that longer distance scenes are reconstructed without using point clouds to supervise the heights. In practice, road surface reconstruction is often used as a module in the auto-labelling task, and the point cloud obtained from the scene reconstruction is usually used to supervise the height.

BTW, to save time, you can even just use a forward-looking short-focus camera, as long as the quality of the reconstruction meets the needs of the downstream task.
